slots:
  cad_isometric: geometry/geometry.png
  geometry_model_orientation: coordinate_systems/coordinate_systems.png
  harmonic_x_accel_plot: vibration_resistance_analysis_x/solution/graphs/frequency_response.png
  harmonic_x_deformation: vibration_resistance_analysis_x/solution/total_deformation.png
  harmonic_x_location: vibration_resistance_analysis_x/loading/acceleration.png
  harmonic_x_stress_asm: vibration_resistance_analysis_x/solution/equivalent_stress.png
  harmonic_x_stress_flange: vibration_resistance_analysis_x/solution/equivalent_stress_flange.png
  harmonic_y_accel_plot: vibration_resistance_analysis_y/solution/graphs/frequency_response.png
  harmonic_y_deformation: vibration_resistance_analysis_y/solution/total_deformation.png
  harmonic_y_location: vibration_resistance_analysis_y/loading/acceleration.png
  harmonic_y_stress_asm: vibration_resistance_analysis_y/solution/equivalent_stress.png
  harmonic_y_stress_flange: vibration_resistance_analysis_y/solution/equivalent_stress_flange.png
  harmonic_z_accel_plot: vibration_resistance_analysis_z/solution/graphs/frequency_response.png
  harmonic_z_deformation: vibration_resistance_analysis_z/solution/total_deformation.png
  harmonic_z_location: vibration_resistance_analysis_z/loading/acceleration.png
  harmonic_z_stress_asm: vibration_resistance_analysis_z/solution/equivalent_stress.png
  harmonic_z_stress_flange: vibration_resistance_analysis_z/solution/equivalent_stress_flange.png
  mesh_global: mesh/mesh.png
  modelling_contacts: connections/connections.png
  shock_minus_x_deformation: equivalent_static_analysis_negx/solution/total_deformation.png
  shock_minus_x_stress_asm: equivalent_static_analysis_negx/solution/equivalent_stress.png
  shock_minus_x_stress_flange: equivalent_static_analysis_negx/solution/equivalent_stress_flange.png
  shock_minus_y_deformation: equivalent_static_analysis_negy/solution/total_deformation.png
  shock_minus_y_stress_asm: equivalent_static_analysis_negy/solution/equivalent_stress.png
  shock_minus_y_stress_flange: equivalent_static_analysis_negy/solution/equivalent_stress_flange.png
  shock_minus_z_deformation: equivalent_static_analysis_negz/solution/total_deformation.png
  shock_minus_z_stress_asm: equivalent_static_analysis_negz/solution/equivalent_stress.png
  shock_minus_z_stress_flange: equivalent_static_analysis_negz/solution/equivalent_stress_flange.png
  shock_plus_x_deformation: equivalent_static_analysis_posx/solution/total_deformation.png
  shock_plus_x_stress_asm: equivalent_static_analysis_posx/solution/equivalent_stress.png
  shock_plus_x_stress_flange: equivalent_static_analysis_posx/solution/equivalent_stress_flange.png
  shock_plus_y_deformation: equivalent_static_analysis_posy/solution/total_deformation.png
  shock_plus_y_stress_asm: equivalent_static_analysis_posy/solution/equivalent_stress.png
  shock_plus_y_stress_flange: equivalent_static_analysis_posy/solution/equivalent_stress_flange.png
  shock_plus_z_deformation: equivalent_static_analysis_posz/solution/total_deformation.png
  shock_plus_z_stress_asm: equivalent_static_analysis_posz/solution/equivalent_stress.png
  shock_plus_z_stress_flange: equivalent_static_analysis_posz/solution/equivalent_stress_flange.png
  static_earth_gravity: static_structural/loading/standard_earth_gravity.png
  static_fixed_support: static_structural/loading/fixed_support.png
  static_pressure: static_structural/loading/pressure.png
  static_total_deformation: static_structural/solution/total_deformation.png
  static_vonmises_flange: static_structural/solution/equivalent_stress_flange.png
  static_vonmises_stress: static_structural/solution/equivalent_stress.png
version: 1
