cad_isometric: "geometry/cad_iso.png"
cad_section: "geometry/cad_section.png"
mesh_global: "mesh/mesh_global.png"
mesh_quality_aspect: "mesh/aspect_ratio.png"
modal_mode1: "modal/mode1.png"
modal_mode2: "modal/mode2.png"
modal_mode3: "modal/mode3.png"
modal_mode4: "modal/mode4.png"
modal_mode5: "modal/mode5.png"
modal_mode6: "modal/mode6.png"
static_total_deformation: "static/total_deformation.png"
static_vonmises_stress: "static/vonmises.png"
static_reaction_force: "static/reaction_force.png"
harmonic_x_bc: "harmonic_x/bc.png"
harmonic_x_amplitude: "harmonic_x/amplitude.png"
harmonic_x_stress: "harmonic_x/stress.png"
